---
title: "hamr - Handle All Missing (Values)"
author: "Duong Vu, Longlingzi Yao, Jordan Dubchak"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{hamr - Handle All Missing (Values)}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

### Introduction

Our package intends to explore the pattern of missing values in users' dataset, imputes the missing values using three simple methods and compare the results of different methods. 

We found *[Amelia](https://cran.r-project.org/web/packages/Amelia/Amelia.pdf)* and *[vis_dat](https://cran.r-project.org/web/packages/visdat/visdat.pdf)* packages that are similar but only visualize the missing data. We thought this would be better package for users who do not have much experience in data wrangling.

# **vis_missing()** 

**Introduction**

explore the pattern of missing values in users' dataset

**Function**

```
vis_missing(df)
```

**Parameters:**

* **df**: a data frame or a numerical matrix with missing values
  * the original dataset with missing values
* **colour**: string 
  * colour scheme for plotting
* **missing_val_char**:
  * the missing value character in the data frame, one of NA, "", " ", "?"

**Return:**

* a heatmap plot

## Example

```
dfm <- data.frame(x = c(1, 2, 3), y = c(0, 10, NaN))
vis_missing(dfm, "", NaN)
```

# **impute_missing()** 

**Introduction:**

imputes the missing values in a specified column with three simple methods: complete case, mean imputation and median imputation

## Function

```
impute_missing(dfm, col, method, missing_val_char)
```

**Parameters:**

* **dfm**: a data frame or a numerical matrix
  * the original dataset with missing values

* **col**: string 
  * a column name

* **method**: string
  * a method name, expected one of "CC", "MIP", "DIP"
  
* **missing_val_char**:
  * the format of the missing value, expected one of NA, NaN, "" and "?"

**Return:**

* a data frame with no missing values in the specified column

## Example

```
dfm <- data.frame(x = c(1, 2, 3), y = c(0, 10, NaN))
impute_missing(dfm, "y", "MIP", NaN)
```

# **compare_model()** 

**Introduction:**

compare the results of different methods

## Function

```
compare_model()
```

**Parameters:**

* **df (ndarray)**: -- the original dataset with missing values

* **Feature (str)**: -- Name of a specified feature from the original dataset 
  * containing missing values that needs to be imputed.
            
* **methods (str or list)**: -- the methods that users want to compare (default: ["CC","IMP"])
  * Supporting methods are: 
        CC 	- Complete Case
        MIP - Imputation with mean value
        DIP - Imputation with median value
* **missing_val_char (str)**: -- missing value types. 
  * Supporting types are:
        "NaN" - Not a Number
        "" - Blank
        "?" - Question mark

**Return:**

* a summary table comparing the summary statistics: count, mean, std, min, 25%, 50%, 75%, max.

## Example

```
dfm <- data.frame(x = c(1, 2, 3), y = c(0, 10, NaN))
compare_model(dfm, "y", "MIP", "NaN")
```
